### ISSUE TITLE
关于出现误码时图片无法还原回来的问题

### ISSUE THREAD

**Issue by Echo-cwb** [BUPT-NextGE/SSCC#1]
您好，在运行代码时，我发现如果是比特流文件的开头的比特出现译码出错时，图片将无法还原，这是不是跟我们读取bpg文件比特流的方法有关系呢

**Comment by Serendipity-55428** [comment]
是这样的，图像格式的头部、尾部会有部分是格式控制位，如果传输过程中被破坏会导致重建的图片格式破坏从而无法打开，如果要保证一定要能还原出图片可以对文件做头保护，我们也有相应的代码，后面会陆续上传，敬请期待

**Comment by Monte2345** [comment]
您好，请问上传了吗？
